parameters:
    mailer_transport: mail
    mailer_encryption: null
    mailer_auth_mode: null
    mailer_host: null
    mailer_user: null
    mailer_password: null
    mailer_sender_address: no-reply@lesciencetour.org
    languages: en|fr
    locale: en
    secret: Th3Sci3nc3T0urS3cr37T0k3n
    root_url: 'http://www.lesciencetour.org'
    db_name: science-tour
    elastica_host: localhost
    elastica_port: 9200
    erasmusLanguages :
        fr: Français
        en: English
        de: Deutsch
    erasmusDomains :
        - youthcommittedforclimate.org
        - ycfc.org
        - erasmus.wexample.com
