the_science_tour_content_pattern:
    resource: "@TheScienceTourContentPatternBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_main:
    resource: "@TheScienceTourMainBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_document:
    resource: "@TheScienceTourDocumentBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_project:
    resource: "@TheScienceTourProjectBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_challenge:
    resource: "@TheScienceTourChallengeBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_event:
    resource: "@TheScienceTourEventBundle/Resources/config/routing.yml"
    prefix:   /

#the_science_tour_user:
#    resource: "@TheScienceTourUserBundle/Resources/config/routing.yml"
#    prefix:   /users

#the_science_tour_message:
#    resource: "@TheScienceTourMessageBundle/Resources/config/routing.yml"
#    prefix:   /

#the_science_tour_map:
#    resource: "@TheScienceTourMapBundle/Resources/config/routing.yml"
#    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

#rem'd for PUGX multi-user bundle
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults:
        _locale: fr
    requirements:
        _locale: en|fr

fos_user_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fullcalendar_loader:
    path: /fc-load-events
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendar }
    options:
        expose: true

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
#    prefix: /exemple
