the_science_tour_user:
    resource: "@TheScienceTourUserBundle/Resources/config/routing.yml"
    prefix:   /users

the_science_tour_project:
    resource: "@TheScienceTourProjectBundle/Resources/config/routing.yml"
    prefix:   /

#the_science_tour_message:
#    resource: "@TheScienceTourMessageBundle/Resources/config/routing.yml"
#    prefix:   /

the_science_tour_map:
    resource: "@TheScienceTourMapBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_event:
    resource: "@TheScienceTourEventBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_document:
    resource: "@TheScienceTourDocumentBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_main:
    resource: "@TheScienceTourMainBundle/Resources/config/routing.yml"
    prefix:   /

the_science_tour_challenge:
    resource: "@TheScienceTourChallengeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

#rem'd for PUGX multi-user bundle
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /

fullcalendar_loader:
    path: /fc-load-events
    defaults: { _controller: ADesignsCalendarBundle:Calendar:loadCalendar }
    options:
        expose: true

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /exemple
