# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

imports:
    # - {resource: @SonataDoctrineMongoDBAdminBundle/Resources/config/doctrine_mongo.xml}
    # - { resource: "@TheScienceTourChallengeBundle/Resources/config/services.yml" }


services:
    # ...
    admin.challenge:
        class: TheScienceTour\ChallengeBundle\Admin\ChallengeAdmin
        arguments: [~, TheScienceTour\ChallengeBundle\Document\Challenge, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: Challenges }
        public: true
    app.is_erasmus:
        class: TheScienceTour\MainBundle\Twig\TheScienceTourErasmusExtension
        tags:
          - { name: twig.extension }
        arguments: ['@session']
    app.request_listener:
        class: TheScienceTour\MainBundle\Listener\TheScienceTourRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: ['@router', '%erasmusDomains%', '%erasmusLanguages%']