# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

imports:
    # - {resource: @SonataDoctrineMongoDBAdminBundle/Resources/config/doctrine_mongo.xml}

services:
    app.is_erasmus:
        class: TheScienceTour\MainBundle\Twig\TheScienceTourErasmusExtension
        tags:
          - { name: twig.extension }
        arguments: ['@session']
    app.request_listener:
        class: TheScienceTour\MainBundle\Listener\TheScienceTourRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
        arguments: ['@router', '%erasmusDomains%', '%erasmusLanguages%']