parameters:

services:
    sonata.admin.user:
        class: TheScienceTour\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, label: User }
        arguments:
            - ~
            - TheScienceTour\UserBundle\Document\User
            - 'SonataAdminBundle:CRUD'
    tst.profile.form.type:
        class: TheScienceTour\UserBundle\Form\Type\ProfileFormType
        arguments: ['%fos_user.model.user.class%']
        tags:
            - { name: form.type, alias: tst_user_profile }