parameters:
#    the_science_tour_message.example.class: TheScienceTour\MessageBundle\Example

services:
#    the_science_tour_message.example:
#        class: %the_science_tour_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
