tst_challenges:
    path: /{_locale}/challenges
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:challenges", _locale: fr }
    requirements:
        _locale: en|fr

tst_challenge_add:
    path: /{_locale}/challenge/add
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:editChallenge", _locale: fr, id: null }
    requirements:
        _locale: en|fr

tst_challenge_edit:
    path: /{_locale}/challenge/{id}/edit
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:editChallenge", _locale: fr }
    requirements:
        _locale: en|fr

tst_challenge:
    path: /{_locale}/challenge/{id}/{tab}
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:challenge", _locale: fr, tab: about }
    requirements:
        _locale: en|fr
        tab: about|rules|resources|chats

tst_challenge_subscribe:
    path: /{_locale}/challenge/{id}/subscribe
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:subscribe", _locale: fr }
    requirements:
        _locale: en|fr

tst_challenge_unsubscribe:
    path: /{_locale}/challenge/{id}/unsubscribe
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:unsubscribe", _locale: fr }
    requirements:
        _locale: en|fr

tst_challenge_add_chat:
    path: /{_locale}/challenge/{id}/addchat
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:addChatMessage", _locale: fr, idchat: null }
    requirements:
        _locale: en|fr

tst_challenge_add_message:
    path: /{_locale}/challenge/{id}/addmessage/{idchat}
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:addChatMessage", _locale: fr }
    requirements:
        _locale: en|fr

tst_challenge_delete_chat:
    path: /{_locale}/challenge/{id}/deletechat/{idchat}
    defaults: { _controller: "TheScienceTourChallengeBundle:Challenge:deleteChat", _locale: fr }
    requirements:
        _locale: en|fr
